/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get products */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "products": [
                         *         {
                         *           "id": 1,
                         *           "title": "iPhone 9",
                         *           "description": "An apple mobile",
                         *           "price": 549,
                         *           "discountPercentage": 12.96,
                         *           "rating": 4.69,
                         *           "stock": 94,
                         *           "brand": "Apple",
                         *           "category": "smartphones",
                         *           "thumbnail": "",
                         *           "images": []
                         *         }
                         *       ],
                         *       "total": 194,
                         *       "skip": 0,
                         *       "limit": 30
                         *     }
                         */
                        "application/json": {
                            products: {
                                id?: number;
                                title?: string;
                                description?: string;
                                price?: number;
                                discountPercentage?: number;
                                rating?: number;
                                stock?: number;
                                brand?: string;
                                category?: string;
                                thumbnail?: string;
                                images?: string[];
                            }[];
                            total: number;
                            skip: number;
                            limit: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** post products */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
